[C4GT] Statement: Added tests for StatementRevoked
dhiway/cord pull request #358
Opened 2024-03-10 20:27 UTC by shashank-iitbhu

added test `trying_to_update_or_revoke_a_revoked_statement_should_fail`
- Verifies that a revoked statement cannot be updated.
- Ensures that a revoked statement cannot be revoked again.
- Checks for appropriate error handling when attempting invalid operations on a revoked statement.

2024-03-11 04:54 UTC, vatsa287 requested changes
Add similar test for `add_presentation` method too.

2024-03-11 17:09 UTC, shashank-iitbhu commented
> Add similar test for `add_presentation` method too.

Hey @vatsa287 , added test for `add_presentation` in the same test which is now renamed to `trying_to_update_or_revoke_or_add_presentation_for_revoked_statement_should_fail`.
Please review.

2024-03-25 06:18 UTC, vatsa287 approved these changes
LGTM

2024-04-01 12:39 UTC, amarts approved these changes

2024-04-01 12:39 UTC, merged