Added test for AlreadyClaimed
dhiway/cord pull request #363
Opened 2024-03-10 23:56 UTC by shashank-iitbhu

Description:
- Added the node with owner1 using a different function that does not add it to the well-known nodes list, but only to the owners' map.
- Then, tried to add the same node as a well-known node with owner2 using the add_well_known_node function.

fixes: #306

2024-03-14 04:58 UTC, vatsa287 requested changes

2024-03-14 04:58 UTC, vatsa287 commented on pallets/node-authorization/src/tests.rs
> +fn add_well_known_node_already_claimed() {
nit: Change name to `adding_already_claimed_well_known_node_should_fail`

2024-03-14 06:49 UTC, shashank-iitbhu commented on pallets/node-authorization/src/tests.rs
> +fn add_well_known_node_already_claimed() {
Done.

2024-04-10 05:02 UTC, vatsa287 approved these changes
LGTM

2024-04-10 05:03 UTC, merged