Rating Identifier already exists tests
dhiway/cord pull request #392
Opened 2024-03-17 10:40 UTC by zeel991

- Fixes https://github.com/dhiway/cord/issues/298
In this test , rating is registered once  , and when rating is registered again , test used different `message id` but same `digest` 
Thus , if the rating Id is already in use , it will give the error `RatingIdentifierAlreadyAdded`
Please give your feedback if I have made any mistake at some point @vatsa287 
Thank you .

2024-03-18 20:27 UTC, zeel991 commented
Hey @vatsa287 , During my previous attempt of writing this test i wrote a test but it gave `messageidalreadyexists` test , so to avoid that I used different message id her , but it is showing some error , can you please just let me know why is the test panicking  , I'll try and solve the issue from your advice .

2024-03-19 03:02 UTC, vatsa287 commented
@zeel991 Will review it today

2024-03-20 06:55 UTC, vatsa287 requested changes
This change is required because there is no other way to reach that block of code, without making explicit change since changing the entry with new `message_id`, or `creator` would create a new `identifier` whereas we require the same `identifier` to be present.

2024-03-20 06:55 UTC, vatsa287 commented on pallets/network-score/src/tests.rs
> +		assert_err!(
Please change to
```
		// Remove message_id and provider_did from entries
		<MessageIdentifiers<Test>>::remove(message_id.clone(), creator.clone());

		assert_err!(Score::register_rating(
			DoubleOrigin(author.clone(), creator.clone()).into(),
			entry.clone(),
			entry_digest,
			message_id.clone(),
			authorization_id.clone(),
			),
			Error::<Test>::RatingIdentifierAlreadyAdded
		);
```

2024-03-20 11:08 UTC, zeel991 commented
Thank you, @vatsa287. I had this approach in the back of my mind, but somehow got confused while implementing it. The test has passed all three tests. If everything seems alright, please assign me the issue before merging the PR.

2024-03-22 05:31 UTC, vatsa287 submitted a review, later dismissed
LGTM

2024-03-22 14:51 UTC, zeel991 commented
@amarts , Please review the PR and give your feedback on it .
Thank you

2024-04-01 12:35 UTC, amarts submitted a review, later dismissed
LGTM

2024-04-02 01:24 UTC, amarts approved these changes

2024-04-02 01:25 UTC, merged