Asset : Added Test For AssetInSameState
dhiway/cord pull request #429
Opened 2024-04-12 18:06 UTC by zeel991

- Fixes https://github.com/dhiway/cord/issues/381
- In the test , I have covered both the cases where the we could get `AssetInSameStatus`
-Please Review the PR and give your feedback

2024-04-13 08:28 UTC, zeel991 commented
Hey @amarts @vatsa287 , the PR has passed all the three tests

2024-04-15 12:05 UTC, vatsa287 requested changes
Please check for both the instances
- When instance-id is provided and asset is in same state,
- When instance-id is not provided, then change status of asset itself, but the given new status is of same status of existing asset.

Above must be done for both status_change & vc_status_change.
So totally 4 places to check the error-code `AssetInSameState`.

2024-04-15 15:28 UTC, zeel991 commented
Hey @vatsa287 , I hope I have completed your required changes 
Please review the PR

2024-04-18 06:55 UTC, vatsa287 requested changes
Few minor comments

2024-04-18 06:55 UTC, vatsa287 commented on pallets/asset/src/tests.rs
> +fn test_asset_status_in_same_state_1() {
```rust
fn changing_status_of_asset_instance_with_same_status_should_fail()

```

2024-04-18 06:55 UTC, vatsa287 commented on pallets/asset/src/tests.rs
> +fn test_asset_status_in_same_state_2() {
```rust
fn changing_status_of_asset_with_same_status_should_fail()

```

2024-04-18 06:55 UTC, vatsa287 commented on pallets/asset/src/tests.rs
> +fn test_vc_asset_status_in_same_state_1() {
```rust
fn changing_status_of_vc_asset_instance_with_same_status_should_fail()

```

2024-04-18 06:55 UTC, vatsa287 commented on pallets/asset/src/tests.rs
> +fn test_vc_asset_status_in_same_state_2() {
```rust
fn changing_status_of_asset_with_same_status_should_fail()

```

2024-04-18 08:45 UTC, zeel991 commented
Hey @vatsa287 , I have made the changes , Please review the PR

2024-04-22 06:16 UTC, vatsa287 approved these changes
LGTM.
Hoping you have gone through this [discussion](https://github.com/dhiway/cord/discussions/396), please start contributing on next level issues other than `good-first-issues`.

2024-04-22 07:49 UTC, zeel991 commented
Hello @amarts , can you please review the PR

2024-04-30 05:56 UTC, zeel991 commented
Hello @amarts , can you please review the PR

2024-05-02 03:51 UTC, smohan-dw commented
LGTM. @zeel991 need to resolve the merge conflicts.

2024-05-03 01:36 UTC, zeel991 commented
> LGTM. @zeel991 need to resolve the merge conflicts.

Done !

2024-05-07 16:42 UTC, zeel991 commented
Hello @amarts sir ,PTAL

2024-06-05 05:09 UTC, amarts approved these changes

2024-06-05 05:10 UTC, merged