Implement MembershipNotFound Error Handling
dhiway/cord pull request #510
Opened 2024-09-25 17:09 UTC by JiyaGupta-cs

Fixes #291 

## Description
This PR enhances the membership management functionality in the pallet-network-membership by introducing tests that validate the behavior of the system when interacting with non-existent memberships. The following tests have been added:

### Test for Revoking Non-Existent Membership:

Implemented the `test_revoke_membership_non_existent` to ensure that attempting to revoke a membership for an account that does not exist correctly raises the MembershipNotFound error.
This test checks that the member count remains unchanged when the revoke operation is attempted on a non-existent account.
Test for Checking Non-Existent Membership:

Added `test_check_membership_non_existent` to verify that the system correctly identifies a non-existent account as not being a member. This ensures the integrity of the membership verification process.
Test for Auto Expiration of Non-Existent Membership:

Included `test_auto_expire_non_existent_membership` to confirm that a non-existent account does not trigger any expiration logic. This test advances the block number to simulate the passage of time and checks that the account remains non-existent.

## Testing 
Tested using ` cargo test -p pallet-network-membership test`

## Screenshots

![image](https://github.com/user-attachments/assets/f781b202-9a56-4081-b6d3-613a79111eac)

2024-09-26 04:47 UTC, vatsa287 requested changes

2024-09-26 04:47 UTC, vatsa287 commented on pallets/network-membership/src/tests.rs
> +		assert!(!NetworkMembership::is_member(&AccountId::new([99u8; 32])));
Use `assert_err` to keep consistency, and can check which error code.

2024-09-26 04:47 UTC, vatsa287 commented on pallets/network-membership/src/tests.rs
> +		assert!(!NetworkMembership::is_member(&AccountId::new([99u8; 32]))); // Should still be false
Use this as well.

2024-09-26 10:35 UTC, JiyaGupta-cs commented
@vatsa287 I have made the changes

2024-09-29 10:55 UTC, JiyaGupta-cs commented
@vatsa287 Please review

2024-10-18 19:49 UTC, JiyaGupta-cs commented
@vatsa287 can you pls review this

2024-10-19 05:32 UTC, vatsa287 approved these changes
LGTM

2024-10-19 05:33 UTC, vatsa287 commented
@amarts 

The tests were not running for this PR for some reason, I had to checkout, rebase & force-push for it to run. Errors are below.

```
[Error](https://github.com/dhiway/cord/actions/runs/11050497895/workflow)
An unexpected error has occurred and we've been automatically notified. Errors are sometimes temporary, so please try again.

If the problem persists, please check whether the Actions service is operating normally at https://githubstatus.com/. If not, please try again once the outage has been resolved.

Should you need to contact Support, please visit https://support.github.com/contact and include request ID: F998:13D251:57E6A5:5EC318:67129E93
```

2024-10-21 15:54 UTC, amarts approved these changes

2024-10-21 15:55 UTC, merged